# Generated by Django 5.2.7 on 2025-11-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='acceptance_criteria',
            field=models.TextField(default='', help_text='Acceptance Criteria'),
        ),
        migrations.AddField(
            model_name='task',
            name='estimate_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('wip', 'In Progress'), ('done', 'Completed')], default='regular', max_length=20),
        ),
    ]
