# Generated by Django 5.2.7 on 2025-11-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_acceptance_criteria_task_estimate_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('regular', 'Regular'), ('low', 'Low')], default='regular', max_length=20),
        ),
    ]
